### ISSUE TITLE
Hash Password Reset Tokens or Switch to JWTs

### ISSUE THREAD

**Issue by jasonzoladz** [agrafix/users#15]
Hi Alex,

First, thanks for putting Spock together.  It's a joy to use: simple, easy to customize.

Second, you might consider a couple changes to the users/users-persistent libs.  
1. Password reset tokens aren't hashed.  As a result, an attacker that acquires the DB might have enough time to compromise accounts before the TTL has expired.  One solution is to bcrypt the tokens.  Another -- I think preferable solution -- is to make password reset stateless via signed JWTs, with configurable TTL.  (In fact, I'd really like to see JWTs made first class citizens in `users` so that we have a session-less authorization option baked into the library.)
2. The bcrypt hash cost is not configurable.  Right now, it's set to 8.  Obviously, the trade-off is security for time.  But for some domains, 8 is perhaps too low.

I'd be happy to do a pull request along these lines, but it involves breaking changes.  Let me know what you think.

Cheers,
Jason

**Comment by agrafix** [comment]
Hi Jason,
1. switching over to JWT sounds good! But I do still think that it's a good idea to have the possibility to revoke tokens on server-side. This could either be done via a blacklist, or one must keep track of all issued JWTs. It would be a good idea to write down the plan first, and then start hacking :-)
2. Sure, we can make bcrypt configurable
- Alex

**Comment by jasonzoladz** [comment]
Unfortunately, the `FromJSON` instance for `(User a)` essentially hard-codes the bcrypt hash cost.  (`parseJSON` takes only the `Object` to be marshalled -- you can't add a `PreferredHashCost` (i.e., `Int`) as a parameter).  And the `FromJSON` instance for `User a` is tightly coupled with the current backends.

So, it likely makes sense that I just roll-my-own auth solution instead of disturbing the entire library . . .

**Comment by agrafix** [comment]
You can always wrap the user with a newtype and implement your own `parseJSON` function.

**Comment by jasonzoladz** [comment]
Good point.

I'm going play with this a bit and see how it works out.
