### ISSUE TITLE
check password without creating tokens?

### ISSUE THREAD

**Issue by unhammer** [agrafix/users#20]
Is there a way to just check the password without creating the token?

**Comment by agrafix** [comment]
Yes! You can use `withAuthUser :: b -> T.Text -> (User -> Bool) -> (UserId b -> IO r) -> IO (Maybe r)` and `makePassword`

**Comment by unhammer** [comment]
Thanks! I ended up with `checkPass b e p = withAuthUser b e (\u -> verifyPassword p (u_password u)) (\_ -> return ()) >>= return.isJust`
