### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by paldepind** [agrafix/users#4]
I'd like to use Users along with the Persistent backend.

The API looks very simple and straightforward. I am, however, having a little trouble figuring out how to instantiate the Persistent backend and wire it together with Users.

I think it would be very helpful for me to see a simple example that initializes the backend and creates a user or something similar.

**Comment by agrafix** [comment]
There's already some ongoing work to use the users package in the example project funblog. You can find it here: https://github.com/agrafix/funblog/issues/8 . It's not complete yet, but I hope to push forward on that end! Maybe the fork in the issue will help you?

**Comment by paldepind** [comment]
It looks great thank you. I will see if I can get it all to work :)
