### ISSUE TITLE
users-persistent: export the Persistent definitions?

### ISSUE THREAD

**Issue by parsonsmatt** [agrafix/users#8]
I imagine that they're not being exported for encapsulation concerns, but it would be nice to query the `Login` table and use definitions with Persistent functions directly.

My use case right now is to `getBy (LoginUsername param)` to get an `Entity Login` from the database. I can do this in the library with `getUserIdByName conn param >>= getUserById conn`, but that would generate two requests to the database.

**Comment by agrafix** [comment]
The alternative would be to find a better abstraction? I've bumped into this issue, too. How about

``` haskell
data UserQuery
     = UserById UserId
     | UserByName String
    -- ...

getUserIdBy :: UserQuery -> ...
getUserBy :: UserQuery -> ...
```

what do you think?

**Comment by parsonsmatt** [comment]
While that would cover this case, it wouldn't let me do eg:

``` haskell
-- models
BlogPost json
    user LoginId
    body Text

-- some handler
getBlogPosts userId =
   runDb $ selectList [ BlogPostUser ==. userId ] []
```

It'd also impede any attempt to use Esqueleto, I think.

`UserQuery` seems like a nicer abstraction to have in the base library, but I'd still want to have the Persistent definitions exported. I think I'd be less inclined to export the implementation details if Persistent were an incidental implementation detail, but if the library is _chosen_ for integrating into a Persistent approach, then exposing that seems like a good idea to me.

**Comment by agrafix** [comment]
You are right, I thought it would be useful to have "interchangable backends", but it does not really make sense - if you move from persistent to postgresql-simple you'll have to refactor your app anyways. If you like, please send a PR to expose this :+1:
